apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cert-manager-acme-dns-issuer
spec:
  acme:
    solvers:
      - dns01:
          cloudflare:
            email: $(certManagerCloudflareEmail)
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
