apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: aimp-cors
  namespace: aimp-cloud
spec:
  headers:
    accessControlAllowMethods:
    - "*"
    accessControlAllowOriginList:
    - "*"
    accessControlAllowHeaders:
    - "*"
    accessControlMaxAge: 100
    addVaryHeader: true
