apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onepanel
parameters:
  replication-type: none
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true