apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: arch
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: admin
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31992
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort
