kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: arch
data:
  fluent.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
    <source>
      @id fluentd-containers.log
      @type tail                              # Fluentd 内置的输入方式，其原理是不停地从源文件中获取新的日志。
      path /var/log/containers/*.log          # 挂载的服务器Docker容器日志地址
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*                    # 设置日志标签
      read_from_head true
      <parse>                                 # 多行格式化成JSON
        @type multi_format                    # 使用 multi-format-parser 解析器插件
        <pattern>
          format json                         # JSON解析器
          time_key time                       # 指定事件时间的时间字段
          time_format %Y-%m-%dT%H:%M:%S.%NZ   # 时间格式
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>
    # 在日志输出中检测异常，并将其作为一条日志转发 
    # https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions
    <match raw.kubernetes.**>           # 匹配tag为raw.kubernetes.**日志信息
      @id raw.kubernetes
      @type detect_exceptions           # 使用detect-exceptions插件处理异常栈信息
      remove_tag_prefix raw             # 移除 raw 前缀
      message log                       
      stream stream                     
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # 添加 Kubernetes metadata 数据
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

    # 修复 ES 中的 JSON 字段
    # 插件地址：https://github.com/repeatedly/fluent-plugin-multi-format-parser
    <filter kubernetes.**>
      @id filter_parser
      @type parser                # multi-format-parser多格式解析器插件
      key_name log                # 在要解析的记录中指定字段名称。
      reserve_data true           # 在解析结果中保留原始键值对。
      remove_key_name_field true  # key_name 解析成功后删除字段。
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

    # 删除一些多余的属性
    <filter kubernetes.**>
      @type record_transformer
      remove_keys $.docker.container_id,$.kubernetes.container_image_id,$.kubernetes.pod_id,$.kubernetes.namespace_id,$.kubernetes.master_url,$.kubernetes.labels.pod-template-hash
    </filter>

    # 只保留具有logging=true标签的Pod日志
    <filter kubernetes.**>
      @id filter_log
      @type grep
      <regexp>
        key $.kubernetes.labels.logging
        pattern ^true$
      </regexp>
    </filter>
    
    <source>
      @type tail
      path /data/logs/ms/*/*.json
      tag aimp-cloud
      read_from_head false
      <parse>
        @type json
      </parse>
    </source>
    
    <filter aimp-cloud.**>
      @type kubernetes_metadata
    </filter>
                 
    <match kubernetes.**>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      include_tag_key true
      host 192.168.20.137
      port 31994
      scheme http
      logstash_format true
      logstash_prefix uat-kubernetes
      request_timeout    30s
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
    
    <match aimp-cloud>
      @id uat-aimp-cloud
      @type elasticsearch
      @log_level info
      include_tag_key true
      host 192.168.20.137
      port 31994
      scheme http
      logstash_format true
      logstash_prefix uat-aimp-cloud
      template_name uat-aimp-cloud
      template_file /etc/fluent/config.d/uat-aimp-cloud.json
      template_overwrite true
      id_key _hash        # specify same key name which is specified in hash_id_key
      remove_keys _hash   # Elasticsearch doesn't like keys that start with _
      <buffer>
        @type file
        path /etc/fluentd/logs/buffers/uat-aimp-cloud-logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
  uat-aimp-cloud.json: |-
    {
      "index_patterns": ["uat-aimp-cloud-*"],
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
      }
    }
  uat-kubernetes.json: |-
    {
      "index_patterns": ["uat-kubernetes-*"],
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
      }
    }
