apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-wildcard-certificate
  namespace: istio-system
spec:
  secretName: onepanel-tls
  issuerRef:
    name: cert-manager-acme-dns-issuer
    kind: ClusterIssuer
  commonName: '*.$(applicationDomain)'
  dnsNames:
  - '*.$(applicationDomain)'