apiVersion: v1
kind: ServiceAccount
metadata:
  name: aimp-report-sa
  namespace: aimp-cloud
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aimp-report-crb
subjects:
- kind: ServiceAccount
  name: aimp-report-sa
  namespace: aimp-cloud
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
