apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: kube-logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fluentd
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: fluentd
  namespace: kube-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: fluentd
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: fluentd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-logging
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: elasticsearch
  namespace: kube-logging
spec:
  clusterIP: None
  ports:
  - name: rest
    port: 9200
  - name: inter-node
    port: 9300
  selector:
    app: elasticsearch
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: kibana
  namespace: kube-logging
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: kibana
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      app.kubernetes.io/managed-by: onepanel-cli
      app.kubernetes.io/part-of: onepanel
  template:
    metadata:
      labels:
        app: kibana
        app.kubernetes.io/managed-by: onepanel-cli
        app.kubernetes.io/part-of: onepanel
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        image: docker.elastic.co/kibana/kibana:7.6.0
        name: kibana
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: es-cluster
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      app.kubernetes.io/managed-by: onepanel-cli
      app.kubernetes.io/part-of: onepanel
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        app.kubernetes.io/managed-by: onepanel-cli
        app.kubernetes.io/part-of: onepanel
    spec:
      containers:
      - env:
        - name: cluster.name
          value: k8s-logs
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: es-cluster-0
        - name: cluster.initial_master_nodes
          value: es-cluster-0
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        image: busybox
        name: fix-permissions
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox
        name: increase-vm-max-map
        securityContext:
          privileged: true
      - command:
        - sh
        - -c
        - ulimit -n 65536
        image: busybox
        name: increase-fd-ulimit
        securityContext:
          privileged: true
  volumeClaimTemplates:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: onepanel
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluentd
    app.kubernetes.io/managed-by: onepanel-cli
    app.kubernetes.io/part-of: onepanel
  name: fluentd
  namespace: kube-logging
spec:
  selector:
    matchLabels:
      app: fluentd
      app.kubernetes.io/managed-by: onepanel-cli
      app.kubernetes.io/part-of: onepanel
  template:
    metadata:
      labels:
        app: fluentd
        app.kubernetes.io/managed-by: onepanel-cli
        app.kubernetes.io/part-of: onepanel
    spec:
      containers:
      - env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: elasticsearch.kube-logging.svc.cluster.local
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: http
        - name: FLUENTD_SYSTEMD_CONF
          value: disable
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        name: fluentd
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      serviceAccount: fluentd
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
