apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service-onepanelcore-onepanel.yaml
  - service-onepanelcoreui-onepanel.yaml
  - istio-envoyfilter-istioingressgatewayauth-istio-system.yaml
patchesStrategicMerge:
  - deployment-onepanelcore-onepanel-patch.yaml