apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 31993
  selector:
    app: redis
  sessionAffinity: None
  type: NodePort
