apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
# These values will be replaced by the CLI, not Kustomize
stringData:
  secretkey: $(metalLbSecretKey)