resources:
- deploy.yaml
- service.yaml
- ingressRoute.yaml
- dind-deploy.yaml
- dind-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cxyacr.azurecr.cn/aimp-cloud/aimp-image
  newTag: "944"
