apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onepanel
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true