apiVersion: v1
kind: Service
metadata:
  labels:
    app: aimp-web
  name: aimp-web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aimp-web
  type: ClusterIP
