
varReference:
- path: spec/jobTemplate/spec/template/spec/containers/args
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/containers/command
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/containers/env/value
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/containers/volumeMounts/mountPath
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/initContainers/args
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/initContainers/command
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/initContainers/env/value
  kind: CronJob

- path: spec/jobTemplate/spec/template/spec/initContainers/volumeMounts/mountPath
  kind: CronJob

- path: spec/template/spec/containers/args
  kind: DaemonSet

- path: spec/template/spec/containers/command
  kind: DaemonSet

- path: spec/template/spec/containers/env/value
  kind: DaemonSet

- path: spec/template/spec/containers/volumeMounts/mountPath
  kind: DaemonSet

- path: spec/template/spec/initContainers/args
  kind: DaemonSet

- path: spec/template/spec/initContainers/command
  kind: DaemonSet

- path: spec/template/spec/initContainers/env/value
  kind: DaemonSet

- path: spec/template/spec/initContainers/volumeMounts/mountPath
  kind: DaemonSet

- path: spec/template/spec/containers/args
  kind: Deployment

- path: spec/template/spec/containers/command
  kind: Deployment

- path: spec/template/spec/containers/env/value
  kind: Deployment

- path: spec/template/spec/containers/volumeMounts/mountPath
  kind: Deployment

- path: spec/template/spec/initContainers/args
  kind: Deployment

- path: spec/template/spec/initContainers/command
  kind: Deployment

- path: spec/template/spec/initContainers/env/value
  kind: Deployment

- path: spec/template/spec/initContainers/volumeMounts/mountPath
  kind: Deployment

- path: spec/rules/host
  kind: Ingress

- path: spec/tls/hosts
  kind: Ingress
  
- path: spec/tls/secretName
  kind: Ingress

- path: spec/template/spec/containers/args
  kind: Job

- path: spec/template/spec/containers/command
  kind: Job

- path: spec/template/spec/containers/env/value
  kind: Job

- path: spec/template/spec/containers/volumeMounts/mountPath
  kind: Job

- path: spec/template/spec/initContainers/args
  kind: Job

- path: spec/template/spec/initContainers/command
  kind: Job

- path: spec/template/spec/initContainers/env/value
  kind: Job

- path: spec/template/spec/initContainers/volumeMounts/mountPath
  kind: Job

- path: spec/containers/args
  kind: Pod

- path: spec/containers/command
  kind: Pod

- path: spec/containers/env/value
  kind: Pod

- path: spec/containers/volumeMounts/mountPath
  kind: Pod

- path: spec/initContainers/args
  kind: Pod

- path: spec/initContainers/command
  kind: Pod

- path: spec/initContainers/env/value
  kind: Pod

- path: spec/initContainers/volumeMounts/mountPath
  kind: Pod

- path: spec/template/spec/containers/args
  kind: ReplicaSet

- path: spec/template/spec/containers/command
  kind: ReplicaSet

- path: spec/template/spec/containers/env/value
  kind: ReplicaSet

- path: spec/template/spec/containers/volumeMounts/mountPath
  kind: ReplicaSet

- path: spec/template/spec/initContainers/args
  kind: ReplicaSet

- path: spec/template/spec/initContainers/command
  kind: ReplicaSet

- path: spec/template/spec/initContainers/env/value
  kind: ReplicaSet

- path: spec/template/spec/initContainers/volumeMounts/mountPath
  kind: ReplicaSet

- path: spec/ports/port
  kind: Service

- path: spec/ports/targetPort
  kind: Service

- path: spec/template/spec/containers/args
  kind: StatefulSet

- path: spec/template/spec/containers/command
  kind: StatefulSet

- path: spec/template/spec/containers/env/value
  kind: StatefulSet

- path: spec/template/spec/containers/volumeMounts/mountPath
  kind: StatefulSet

- path: spec/template/spec/initContainers/args
  kind: StatefulSet

- path: spec/template/spec/initContainers/command
  kind: StatefulSet

- path: spec/template/spec/initContainers/env/value
  kind: StatefulSet

- path: spec/template/spec/initContainers/volumeMounts/mountPath
  kind: StatefulSet

  # Additions
- path: spec/acme/email
  kind: ClusterIssuer

- path: spec/commonName
  kind: Certificate

- path: spec/dnsNames
  kind: Certificate

- path: spec/acme/solvers/dns01/route53/region
  kind: ClusterIssuer

- path: spec/acme/solvers/dns01/route53/accessKeyID
  kind: ClusterIssuer

- path: spec/servers/hosts
  kind: Gateway

- path: spec/template/spec/containers/image
  kind: StatefulSet

- path: spec/volumeClaimTemplates/spec/resources/requests/storage
  kind: StatefulSet

- path: metadata/name
  kind: Namespace

- path: metadata/namespace
  kind: NetworkPolicy

- path: metadata/namespace
  kind: Application

- path: metadata/namespace
  kind: Role

- path: metadata/namespace
  kind: RoleBinding

- path: metadata/namespace
  kind: Secret

- path: stringData
  kind: Secret

- path: subjects/namespace
  kind: RoleBinding

- path: data/namespace
  kind: ConfigMap
  # End Additions

- path: metadata/labels
