apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: arch
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - argocd.uat.aimpcloud.cn
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server
        port:
          number: 80
